name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Yarn
        run: corepack enable

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Type Check
        run: yarn typecheck

      - name: Lint
        run: yarn lint:check

      - name: Format Check
        run: yarn format:check
